from enum import Enum

# Define ALU operations as an Enum for type safety
class Operation(Enum):
    ADD = "ADD"
    SUB = "SUB"
    MOV = "MOV"
    LOAD = "LOAD"
    STORE = "STORE"
    MOVSEG = "MOVSEG"
    AND = "AND"
    OR = "OR"
    XOR = "XOR"
    NOT = "NOT"
    SHL = "SHL"
    SHR = "SHR"
    ROL = "ROL"
    ROR = "ROR"
    CMP = "CMP"
    JMP = "JMP"
    JE = "JE"
    JNE = "JNE"
    JG = "JG"
    JL = "JL"
    PUSH = "PUSH"
    POP = "POP"
    IN = "IN"
    OUT = "OUT"
    INC = "INC"
    DEC = "DEC"
